#!/bin/sh
export GOOGLEAPPENGINE=/usr/local/google_appengine
export PYTHONPATH=$GOOGLEAPPENGINE:$GOOGLEAPPENGINE/lib:$GOOGLEAPPENGINE/lib/webapp2:$GOOGLEAPPENGINE/lib/webob_1_1_1:$GOOGLEAPPENGINE/lib/jinja2:$GOOGLEAPPENGINE/lib/yaml/lib
